### ISSUE TITLE
Not Pulling TV Show Metadata Correctly

### ISSUE THREAD

**Issue by cmgfender** [piplongrun/OpenMovieDatabase.bundle#16]
@Piplongrun Show titles and ratings not being pulled in after latest update to 1.6
[com.plexapp.agents.omdbapi.log](https://github.com/piplongrun/OpenMovieDatabase.bundle/files/2142151/com.plexapp.agents.omdbapi.log)

**Comment by cmgfender** [comment]
[com.plexapp.agents.omdbapi logs.txt](https://github.com/piplongrun/OpenMovieDatabase.bundle/files/2150627/com.plexapp.agents.omdbapi.logs.txt)

added additional logs

**Comment by piplongrun** [comment]
Thanks for the information! The issue has been fixed with an extra check (https://github.com/piplongrun/OpenMovieDatabase.bundle/commit/a69d915e2f2114e6d7e68eca99a2462ed0fff2af).

**Comment by cmgfender** [comment]
question. its working much more reliably, but random episodes are still not pulling Metadata or rating . 90% of shows and episodes do now. and its mostly NEWER episodes. is this just due to not being available on omdb yet? can post more logs

**Comment by piplongrun** [comment]
I can't say for sure, but it can be 1 of 2 things: one of the backend servers is timing out due to high load or, more plausible, the info is not yet available in OMDB.

**Comment by cmgfender** [comment]
@piplongrun dont know if i need to tag you to see a message on a closed issue!

**Comment by piplongrun** [comment]
I am looking into a (optional) fallback option where title and description will be filled in with data from e.g. TVmaze if OMDB does not return data (`null`) or title is something like `Episode #1.1`

**Comment by cmgfender** [comment]
Thats awesome! Thanks for all your hard work on this.

-- 
Chuck Glassmire
